Repository gardener/kupid, pull requests merged in 2023-03, with the labels that each got.

#45 Added a doc evaluating Kyverno as a replacement
  docs/Kyverno Evaluation.md
Labels: lifecycle/stale, reviewed/lgtm, needs/ok-to-test, size/m

#51 Adapt high-availability configuration
  charts/gardener-extension-kupid/templates/deployment.yaml
  charts/gardener-extension-kupid/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
Labels: area/high-availability, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/xs

#52 Fix metrics port in service
  charts/gardener-extension-kupid/templates/deployment.yaml
  charts/gardener-extension-kupid/templates/service.yaml
  charts/gardener-extension-kupid/values.yaml
  config/webhook/service.yaml
  example/controller-registration.yaml
Labels: kind/bug, reviewed/lgtm, needs/ok-to-test, size/xs

#50 Adapt `NetworkPolicy`s according to recent refactorings
  charts/gardener-extension-kupid/templates/deployment.yaml
  charts/gardener-extension-kupid/templates/service.yaml
  example/controller-registration.yaml
Labels: area/dev-productivity, area/networking, area/ops-productivity, area/security, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/xs

#54 Make webhook failure policy configurable and improve logging
  api/v1alpha1/zz_generated.deepcopy.go
  charts/gardener-extension-kupid/doc.go
  charts/gardener-extension-kupid/templates/deployment.yaml
  charts/gardener-extension-kupid/values.yaml
  example/controller-registration.yaml
  hack/boilerplate.go.txt
  main.go
  pkg/webhook/webhook.go
Labels: area/logging, area/usability, kind/bug, needs/ok-to-test, needs/changes, needs/review, size/s, merge/squash
